module Main where

import Text.Printf

import qualified Problem1
import qualified Problem2
import qualified Problem3
import qualified Problem4
import qualified Problem5
import qualified Problem6

answer :: Int -> String -> IO ()
answer value desc =
  printf "\n%s\n\n\x1b[32mAnswer: %d\x1b[39m\n\n" desc value


main :: IO ()
main = do
    answer Problem1.answer "\
    \If we list all the natural numbers below 10 that are multiples of 3 or 5,\
    \we get 3, 5, 6 and 9. The sum of these multiples is 23.\
    \\n\
    \Find the sum of all the multiples of 3 or 5 below 1000."

    answer Problem2.answer "\
    \Each new term in the Fibonacci sequence is generated by adding the previous two terms. \
    \By starting with 1 and 2, the first 10 terms will be:\
    \\n\
    \\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\
    \\n\
    \By considering the terms in the Fibonacci sequence whose values do not exceed four million,\
    \find the sum of the even-valued terms."

    answer Problem3.answer "\
    \The prime factors of 13195 are 5, 7, 13 and 29.\
    \\n\
    \What is the largest prime factor of the number 600851475143 ?"

    answer Problem4.answer "\
    \A palindromic number reads the same both ways. \
    \The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.\
    \\n\
    \Find the largest palindrome made from the product of two 3-digit numbers."

    answer Problem5.answer "\
    \2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.\
    \\n\
    \What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"

    answer Problem6.answer "\
    \The sum of the squares of the first ten natural numbers is, 12 + 22 + ... + 102 = 385\n\n\
    \The square of the sum of the first ten natural numbers is, (1 + 2 + ... + 10)2 = 552 = 3025\n\n\
    \Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.\
    \\n\
    \Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum."
